<a href="https://colab.research.google.com/github/DinhThanh-Dat/ThucHanhDeepLearning/blob/main/Baitaptuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
# tao numpy arry
# mang 1 chieu
mylist = [1,2,3,4]
print('Python list',mylist)
numpy_arr = np.array(mylist)
print('Numpy array',numpy_arr)
print('==================\n')

#mang 2 chieu
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)
print('==================\n')

#mang 3 chieu
d=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(d)
print(d.shape)

Python list [1, 2, 3, 4]
Numpy array [1 2 3 4]

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [10]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1
e=np.zeros((2,2))
f=np.ones((4,4))
print('Zero: \n',e)
print('One: \n',f)


Zero: 
 [[0. 0.]
 [0. 0.]]
One: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
#Thay đổi kích thước ma trận
e=np.array([[1,2,3],[4,5,6]])
print(e)

f=e.reshape(3,2)
print('Reshape: \n',f)
print('============\n')
g = np.array([[(1,2,3),(4,5,6)],
             [(7,8,9),(10,11,12)]
             ])
print(g)
print('reshape:\n',g.shape)

h = g.reshape(3,4)
print('reshape(3,4):\n',h)

j = g.reshape(3,2,2)
print('reshape(3,2,2):\n',j)

k=g.reshape(2,3,2)
print('reshape(2,3,2):\n',k)


[[1 2 3]
 [4 5 6]]
Reshape: 
 [[1 2]
 [3 4]
 [5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
reshape:
 (2, 2, 3)
reshape(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape(3,2,2):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
reshape(2,3,2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
#chuyển array nhiều chiều về 1 chiều
e=np.array([(1,2,3),(4,5,6)])
f=e.flatten()
print(f)

g=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
j=g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
#Thêm dòng dữ liệu với hstack và vstack
f=np.array([(1,2,3),(4,5,6)])
g=np.array([(7,8,9),(10,11,12)])
h=np.vstack((f,g))
print('Horizontal Append\n',h)
i=np.hstack((f,g))
print('Vertical Append\n',i)

Horizontal Append
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vertical Append
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
