<a href="https://colab.research.google.com/github/DinhThanh-Dat/ThucHanhDeepLearning/blob/main/Baitaptuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bai Numpy

##3.1.Tạo array 1-chiều, 2-chiều, 3 chiều

In [ ]:
import numpy as np
# tao numpy arry
# mang 1 chieu
mylist = [1,2,3,4]
print('Python list',mylist)
numpy_arr = np.array(mylist)
print('Numpy array',numpy_arr)
print('==================\n')

#mang 2 chieu
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)
print('==================\n')

#mang 3 chieu
d=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(d)
print(d.shape)

Python list [1, 2, 3, 4]
Numpy array [1 2 3 4]

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


##3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [ ]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1
e=np.zeros((2,2))
f=np.ones((4,4))
print('Zero: \n',e)
print('One: \n',f)


Zero: 
 [[0. 0.]
 [0. 0.]]
One: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##3.5. Reshape và Flatten ma trận
###3.5.1. Reshape thay đổi kích thước ma trận

In [ ]:
#Thay đổi kích thước ma trận
e=np.array([[1,2,3],[4,5,6]])
print(e)

f=e.reshape(3,2)
print('Reshape: \n',f)
print('============\n')
g = np.array([[(1,2,3),(4,5,6)],
             [(7,8,9),(10,11,12)]
             ])
print(g)
print('reshape:\n',g.shape)

h = g.reshape(3,4)
print('reshape(3,4):\n',h)

j = g.reshape(3,2,2)
print('reshape(3,2,2):\n',j)

k=g.reshape(2,3,2)
print('reshape(2,3,2):\n',k)


[[1 2 3]
 [4 5 6]]
Reshape: 
 [[1 2]
 [3 4]
 [5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
reshape:
 (2, 2, 3)
reshape(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape(3,2,2):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
reshape(2,3,2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


###3.5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [ ]:
#chuyển array nhiều chiều về 1 chiều
e=np.array([(1,2,3),(4,5,6)])
f=e.flatten()
print(f)

g=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
j=g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


##3.6. Thêm dòng dữ liệu với hstack và vstack

In [ ]:
#Thêm dòng dữ liệu với hstack và vstack
f=np.array([(1,2,3),(4,5,6)])
g=np.array([(7,8,9),(10,11,12)])
h=np.vstack((f,g))
print('Horizontal Append\n',h)
i=np.hstack((f,g))
print('Vertical Append\n',i)

Horizontal Append
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vertical Append
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


##3.7. Sinh mảng số ngẫu nhiên
###3.7.1. Sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np
a = np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b = np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c = np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [69 91 38 66 74]
Random 2-D array
 [[33 83 19 51]
 [69 23  4 98]
 [14 40 21 17]]
Random 3-D array
 [[[21 25 48]
  [76 55 59]
  [41 87 14]
  [13 67 74]]

 [[ 3 61 28]
  [27  2 91]
  [ 3 54 84]
  [15 97 74]]

 [[91 43 16]
  [93 66 56]
  [87 77 13]
  [62 59 66]]]


##3.7.2. Sinh mảng số thực trong khoảng [0, 1]

In [ ]:
a = np.random.rand(5)
print('Random 1-D array\n',a)
b = np.random.rand(3,4)
print('Random 2-D array\n',b)
c = np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.31792836 0.42082683 0.61340472 0.97502243 0.59683843]
Random 2-D array
 [[0.29476278 0.41576578 0.28837485 0.39984892]
 [0.65343521 0.74220514 0.08314377 0.52393819]
 [0.70957077 0.20180779 0.40804613 0.69971831]]
Random 3-D array
 [[[0.77164265 0.73569035 0.32925238]
  [0.89637054 0.93499516 0.7098429 ]
  [0.07024965 0.55263389 0.11991733]
  [0.15391967 0.0431022  0.22925579]]

 [[0.99734518 0.41614728 0.37595022]
  [0.54451991 0.07175131 0.2240159 ]
  [0.35897071 0.67449539 0.86089888]
  [0.98134568 0.71840127 0.45835358]]

 [[0.98959303 0.15679683 0.66366364]
  [0.22428254 0.29129992 0.48470037]
  [0.74557544 0.85980994 0.30611892]
  [0.56392906 0.21852149 0.98742839]]]


###3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
a = np.random.normal(5,0.5,10)
print(a)

[4.41723719 5.72652408 4.35549481 4.83435475 5.08017554 5.31240972
 5.3565249  4.66766965 4.85726617 4.85193152]


###3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)

b = np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)

8
[[12 18  2  8 16]
 [12 10 10 20  6]
 [ 8 16 10  8  8]]


##3.8. Thay đổi giá trị của ma trận

In [ ]:
A = np.matrix(np.ones((5,5)))
print('The matrix\n',A)
np.array(A)[2] = 2
print('Change values of third row with array\n',A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##3.9. Sinh dãy số theo khoảng cho trước
###3.9.1. Dùng hàm arange

In [ ]:
#tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1,20)
print(a)

#tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1,20,2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


###3.9.2. Dùng hàm linspace

In [ ]:
a = np.linspace(1,5,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


##3.10. Index và slice

In [ ]:
#slide
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:',a[0])
print('second row:',a[1])

#indexing
print('second column:',a[:,1])
print('first column:',a[:,0])
print('First two values of second row:', a[1,:2])



[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


#Bai PANDAS
##Series là cấu trúc dữ liệu 1-chiều.

In [ ]:
import pandas as pd
#Tao pandas series tư list
a = pd.Series([1,2,3])
print(a)
print('First value:', a[0])
b = pd.Series([1,2,3],index=['a','b','c'])
print(b)
print('First value:',b['a'])
#Tao pandas series tu dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1
1    2
2    3
dtype: int64
First value: 1
a    1
b    2
c    3
dtype: int64
First value: 1
day1    420
day2    380
day3    390
dtype: int64


##TẠO ĐỐI TƯỢNG DATAFRAME
###DataFrame là mảng 2-chiều có nhãn ở 2 trục

In [ ]:
h = np.array([[1,2],[3,4]])
df_h = pd.DataFrame(h)
print('DataFrame\n',df_h)

numpy_h = np.array(df_h)
print('Munpy array:\n',numpy_h)

DataFrame
    0  1
0  1  2
1  3  4
Munpy array:
 [[1 2]
 [3 4]]


###Tạo DataFrame mảng 2-chiều có tên cột

In [ ]:
dic = {'Name':['John', 'Smith'],'Age':[30,40]}
df = pd.DataFrame(dic)
print(df)

#tao mang 20 x 4
r = np.random.randn(20,4)
df = pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head()) # in 5 dong dau tien
#


    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0 -0.596673  0.717880  0.473530 -0.665171
1  0.913026 -1.400002 -1.123679 -0.961991
2 -0.862822 -0.226439 -1.181613 -0.139259
3 -0.836565 -0.178001 -0.668313 -0.656787
4 -0.559978  2.210645  0.646549 -0.009999


###Slice DataFrame

In [ ]:
#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  #in 5 dòng đầu tiên

#chọn 1 cột
print('Chọn cột so1\n', df['so1'])

#chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

#chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

#chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

#Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -1.067409  0.244046  1.176908  0.023624
1 -0.244754  1.081917  1.216733 -1.706044
2 -1.366678  1.610019  0.649939  0.116620
3  2.040210  0.551901 -0.058917  1.289878
4 -0.150427 -0.080637  0.660934 -2.036406
Chọn cột so1
 0    -1.067409
1    -0.244754
2    -1.366678
3     2.040210
4    -0.150427
5    -0.115337
6    -0.179948
7    -1.141463
8     1.077770
9     0.651259
10   -0.763751
11    1.022841
12   -0.944834
13    1.064817
14    0.014561
15    1.933591
16    0.642434
17   -0.784759
18   -1.617846
19   -1.091596
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -1.067409  0.244046  1.176908  0.023624
1 -0.244754  1.081917  1.216733 -1.706044
2 -1.366678  1.610019  0.649939  0.116620
Chọn nhiều cột
          so1       so3
0  -1.067409  1.176908
1  -0.244754  1.216733
2  -1.366678  0.649939
3   2.040210 -0.058917
4  -0.150427  0.660934
5  -0.115337 -0.103147
6  -0.179948 -0.597528
7  -1.141463  0.012153


##7.1. Nối nhiều DataFrame

In [ ]:
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])

df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

#Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

#Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


##7.2. Đọc dữ liệu từ CSV

In [ ]:
# Đọc dữ liệu từ CSV
path = '/content/sample_data/Salary_Data.csv'
COLUMNS = ['YearsExperience', 'Salary']

df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)

df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

##7.3. Gom nhóm dữ liệu DataFrame

In [ ]:
#Gom nhóm dữ liệu trong DataFrame
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())

print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

##8. BÀI TẬP

1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [31]:
import numpy as np

arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng được tạo ngẫu nhiên:")
print(arr)

check_all_nonzero = np.all(arr)

print("\nTất cả các phần tử có khác 0 không?")
if check_all_nonzero:
    print("Có, tất cả các phần tử đều khác 0.")
else:
    print("Không, trong mảng có ít nhất một phần tử bằng 0.")

Mảng được tạo ngẫu nhiên:
[[16  9  9]
 [11  6  4]
 [ 2 14 14]]

Tất cả các phần tử có khác 0 không?
Có, tất cả các phần tử đều khác 0.


2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [32]:
import numpy as np

# 1. Tạo mảng ngẫu nhiên kích thước 3x3 với giá trị trong khoảng [0, 20]
# Để bao gồm cả số 20, ta đặt tham số high là 21
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng được tạo ngẫu nhiên:")
print(arr)

# 2. Kiểm tra xem có tồn tại ít nhất một phần tử khác 0 hay không
# Cách 1: Sử dụng trực tiếp mảng (0 là False, khác 0 là True)
has_nonzero = np.any(arr)

# Cách 2: Viết điều kiện rõ ràng để dễ đọc
# has_nonzero = np.any(arr != 0)

print("\nCó tồn tại phần tử nào khác 0 trong mảng không?")
if has_nonzero:
    print("Có, tồn tại ít nhất một phần tử khác 0.")
else:
    print("Không, tất cả các phần tử trong mảng đều bằng 0.")

Mảng được tạo ngẫu nhiên:
[[ 9  0 19]
 [ 2  8 20]
 [ 0 15 13]]

Có tồn tại phần tử nào khác 0 trong mảng không?
Có, tồn tại ít nhất một phần tử khác 0.


3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [33]:
import numpy as np

# --- 1. SO SÁNH MẢNG 1 CHIỀU ---
print("--- So sánh mảng 1 chiều ---")
a1 = np.array([10, 20, 30])
b1 = np.array([15, 20, 25])

print(f"Mảng a1: {a1}")
print(f"Mảng b1: {b1}")

print("a1 > b1  (greater):      ", np.greater(a1, b1))
print("a1 >= b1 (greater_equal):", np.greater_equal(a1, b1))
print("a1 < b1  (less):         ", np.less(a1, b1))
print("a1 <= b1 (less_equal):   ", np.less_equal(a1, b1))

print("\n" + "-"*30 + "\n")

# --- 2. SO SÁNH MẢNG 2 CHIỀU ---
print("--- So sánh mảng 2 chiều ---")
a2 = np.array([[1, 5],
               [8, 12]])

b2 = np.array([[2, 4],
               [8, 10]])

print("Ma trận a2:\n", a2)
print("Ma trận b2:\n", b2)

# Thực hiện so sánh
print("\na2 > b2 (Greater):\n", np.greater(a2, b2))
print("\na2 >= b2 (Greater Equal):\n", np.greater_equal(a2, b2))
print("\na2 < b2 (Less):\n", np.less(a2, b2))
print("\na2 <= b2 (Less Equal):\n", np.less_equal(a2, b2))

--- So sánh mảng 1 chiều ---
Mảng a1: [10 20 30]
Mảng b1: [15 20 25]
a1 > b1  (greater):       [False False  True]
a1 >= b1 (greater_equal): [False  True  True]
a1 < b1  (less):          [ True False False]
a1 <= b1 (less_equal):    [ True  True False]

------------------------------

--- So sánh mảng 2 chiều ---
Ma trận a2:
 [[ 1  5]
 [ 8 12]]
Ma trận b2:
 [[ 2  4]
 [ 8 10]]

a2 > b2 (Greater):
 [[False  True]
 [False  True]]

a2 >= b2 (Greater Equal):
 [[False  True]
 [ True  True]]

a2 < b2 (Less):
 [[ True False]
 [False False]]

a2 <= b2 (Less Equal):
 [[ True False]
 [ True False]]


4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [34]:
import numpy as np

# 1. Tạo 10 số 0
zeros = np.zeros(10)

# 2. Tạo 10 số 1
ones = np.ones(10)

# 3. Tạo 10 số 5
# (Tạo mảng 10 số 1 rồi nhân với 5)
fives = np.ones(10) * 5

# 4. Kết hợp các mảng lại với nhau
result = np.concatenate([ones, zeros, fives])

print("Mảng kết quả:")
print(result)

# Kiểm tra kích thước mảng
print("\nKích thước mảng:", result.size)

Mảng kết quả:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]

Kích thước mảng: 30


5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [35]:

# Sử dụng np.arange(start, stop, step)
# start = 30 (bắt đầu từ 30)
# stop  = 71 (để bao gồm cả số 70, vì tham số stop không lấy giá trị cuối)
# step  = 2  (bước nhảy là 2 để lấy các số chẵn)

arr_even = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(arr_even)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
(Tìm hiểu hàm identity của numpy)

In [36]:
# Sử dụng np.identity(n) để tạo ma trận đơn vị kích thước n x n
# n = 3 cho ma trận 3x3
matrix_identity = np.identity(3)

print("Ma trận đơn vị 3x3 (sử dụng np.identity):")
print(matrix_identity)

# Cách khác: Sử dụng np.eye(N, M)
# (np.eye linh hoạt hơn vì có thể tạo ma trận không vuông)
matrix_eye = np.eye(3)

print("\nMa trận đơn vị 3x3 (sử dụng np.eye):")
print(matrix_eye)

Ma trận đơn vị 3x3 (sử dụng np.identity):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Ma trận đơn vị 3x3 (sử dụng np.eye):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử
đầu và cuối

In [37]:
# 1. Tạo mảng trong khoảng [15, 55]
# Dùng np.arange(15, 56) để bao gồm cả số 55
# Ở đây tôi tạo mảng đầy đủ rồi lấy 10 phần tử đầu tiên để đúng yêu cầu "10 phần tử"
# Hoặc dùng np.linspace nếu bạn muốn 10 phần tử cách đều nhau trong khoảng đó.

arr = np.arange(15, 25) # Ví dụ tạo 10 phần tử từ 15 đến 24
# Hoặc: arr = np.linspace(15, 55, 10) # Tạo chính xác 10 số từ 15 đến 55

print("Mảng ban đầu (10 phần tử):")
print(arr)

# 2. In các giá trị ngoại trừ phần tử đầu và cuối
# Sử dụng slicing [1:-1]
# 1: Bắt đầu từ index 1 (phần tử thứ hai)
# -1: Dừng lại trước index cuối cùng
result = arr[1:-1]

print("\nCác giá trị ngoại trừ phần tử đầu và cuối:")
print(result)

Mảng ban đầu (10 phần tử):
[15 16 17 18 19 20 21 22 23 24]

Các giá trị ngoại trừ phần tử đầu và cuối:
[16 17 18 19 20 21 22 23]


8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong
khoảng [9, 15]

In [38]:
# 1. Tạo mảng 20 phần tử trong khoảng [0, 20]
# Sử dụng np.linspace để lấy đúng 20 số cách đều nhau từ 0 đến 20
arr = np.linspace(0, 20, 20)

print("Mảng ban đầu:")
print(arr)

# 2. Đổi dấu các số nằm trong khoảng [9, 15]
# Tạo một mặt nạ điều kiện (mask): (arr >= 9) VÀ (arr <= 15)
condition = (arr >= 9) & (arr <= 15)

# Đổi dấu trực tiếp bằng cách nhân với -1 tại các vị trí thỏa mãn điều kiện
arr[condition] *= -1

print("\nMảng sau khi đổi dấu các phần tử trong khoảng [9, 15]:")
print(arr)

Mảng ban đầu:
[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]

Mảng sau khi đổi dấu các phần tử trong khoảng [9, 15]:
[  0.           1.05263158   2.10526316   3.15789474   4.21052632
   5.26315789   6.31578947   7.36842105   8.42105263  -9.47368421
 -10.52631579 -11.57894737 -12.63157895 -13.68421053 -14.73684211
  15.78947368  16.84210526  17.89473684  18.94736842  20.        ]


9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]

In [39]:
# Sử dụng np.random.randint(low, high, size)
# low = 10 (giá trị nhỏ nhất có thể nhận)
# high = 22 (giá trị biên trên, vì NumPy không lấy giá trị này, nên dùng 22 để có thể xuất hiện số 21)
# size = (3, 4) (kích thước ma trận: 3 hàng, 4 cột)

matrix = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3x4 với các giá trị từ 10 đến 21:")
print(matrix)

Ma trận 3x4 với các giá trị từ 10 đến 21:
[[17 12 13 11]
 [12 14 16 17]
 [17 19 12 12]]


10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có
giá trị 0

In [40]:
# 1. Tạo ma trận 10x10 toàn số 1
matrix = np.ones((10, 10))

# 2. Thay thế các phần tử bên trong thành số 0
# Slicing [1:-1, 1:-1] có nghĩa là:
# - Về hàng: lấy từ hàng index 1 đến hàng sát cuối (bỏ hàng đầu và cuối)
# - Về cột: lấy từ cột index 1 đến cột sát cuối (bỏ cột đầu và cuối)
matrix[1:-1, 1:-1] = 0

print("Ma trận 10x10 với biên là 1 và bên trong là 0:")
print(matrix)

Ma trận 10x10 với biên là 1 và bên trong là 0:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu
hàm diag của numpy)

In [41]:
# 1. Tạo danh sách các giá trị muốn đặt trên đường chéo chính
values = [1, 2, 3, 4, 5]

# 2. Sử dụng np.diag để tạo ma trận 5x5 từ danh sách trên
# Các phần tử không nằm trên đường chéo chính sẽ tự động bằng 0
matrix_diag = np.diag(values)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(matrix_diag)

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum
của numpy)

In [42]:
# 1. Tạo mảng 3x3x3 với các số nguyên ngẫu nhiên từ 1 đến 10
arr_3d = np.random.randint(1, 11, size=(3, 3, 3))

print("Mảng 3x3x3 được tạo ra:")
print(arr_3d)

# 2. Tính tổng theo mỗi dòng (axis=1)
# Kết quả sẽ là tổng của các hàng trong từng ma trận con
sum_rows = np.sum(arr_3d, axis=1)

# 3. Tính tổng theo mỗi cột (axis=2)
# Kết quả sẽ là tổng của các cột trong từng ma trận con
sum_cols = np.sum(arr_3d, axis=2)

print("\n--- KẾT QUẢ TÍNH TOÁN ---")
print("Tổng theo mỗi dòng (kết quả mỗi tầng là một mảng 1x3):")
print(sum_rows)

print("\nTổng theo mỗi cột (kết quả mỗi tầng là một mảng 1x3):")
print(sum_cols)

Mảng 3x3x3 được tạo ra:
[[[ 7  3  2]
  [10  6 10]
  [ 9  8  1]]

 [[ 3  6  2]
  [ 8  6  3]
  [ 4  6  7]]

 [[ 5  7  7]
  [ 2  1 10]
  [ 8  9  2]]]

--- KẾT QUẢ TÍNH TOÁN ---
Tổng theo mỗi dòng (kết quả mỗi tầng là một mảng 1x3):
[[26 17 13]
 [15 18 12]
 [15 17 19]]

Tổng theo mỗi cột (kết quả mỗi tầng là một mảng 1x3):
[[12 26 18]
 [11 17 17]
 [19 13 19]]


#Bai TENSORFLOW
##Tensor 0-chiều

In [ ]:
import tensorflow as tf

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# This will be an int32 tensor by default;
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


## Tensor 1-chiều

In [ ]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


##Tensor 2-chiều (ma trận)

In [ ]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


##Tensor n-chiều (nhiều trục)

In [ ]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


##Tạo tensor tự động gán giá trị 0 ban đầu

In [ ]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


##Tạo tensor tự động gán giá trị 1 ban đầu

In [ ]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


##Tạo tensor tự động với giá trị bất kỳ

In [ ]:
t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


##Tạo tensor 1-chiều với hàm linspace

In [ ]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


##Tạo tensor 1-chiều với hàm range

In [ ]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)


range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


##3.11. Tạo tensor với giá trị ngẫu nhiên

In [4]:

range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([ 0.0124386   0.36191794  2.1731014  -0.07258418 -1.8270957 ], shape=(5,), dtype=float32)


In [5]:
range_tensor = tf.random.normal([3,3])
print(range_tensor)

tf.Tensor(
[[-1.0205067  -1.1185253  -1.2075816 ]
 [-0.55726933 -1.122265    0.28871188]
 [-1.2576934   0.22089222 -0.25129813]], shape=(3, 3), dtype=float32)


In [6]:
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

tf.Tensor([-0.93959117  0.39430243  0.12316041  1.5699466  -1.5486352 ], shape=(5,), dtype=float32)


In [7]:
range_tensor = tf.random.truncated_normal([3,2])
print(range_tensor)

tf.Tensor(
[[ 0.8625798   0.7930207 ]
 [ 0.17993836 -1.0879866 ]
 [ 0.6434537  -0.42851788]], shape=(3, 2), dtype=float32)


In [8]:
range_tensor = tf.random.truncated_normal([3,2,2])
print(range_tensor)

tf.Tensor(
[[[-0.42471096  0.7891487 ]
  [-0.19770432 -0.8180212 ]]

 [[-0.8681521   1.4222351 ]
  [ 0.2336684  -0.93629515]]

 [[ 0.21124974  1.5728701 ]
  [ 0.8325392  -0.20229524]]], shape=(3, 2, 2), dtype=float32)


In [9]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor([17.785587 18.954676 14.593812 19.912828 15.219727], shape=(5,), dtype=float32)


In [10]:
range_tensor = tf.random.uniform([3,2], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[19.139206 19.415966]
 [13.522148 18.77469 ]
 [12.214283 11.987299]], shape=(3, 2), dtype=float32)


In [11]:
range_tensor = tf.random.uniform([3,2,5], minval=10, maxval=20)
print(range_tensor)


tf.Tensor(
[[[11.6266775 17.107124  10.520012  17.624289  17.247303 ]
  [14.456409  16.583931  13.615881  18.752556  11.384245 ]]

 [[15.991287  18.135872  10.730601  14.688929  10.047818 ]
  [15.848702  10.764545  19.738367  10.0960865 15.554109 ]]

 [[13.6413    11.904941  11.458679  10.305466  18.4976   ]
  [18.989958  10.50029   10.9768505 13.515147  18.191807 ]]], shape=(3, 2, 5), dtype=float32)


In [12]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([13.060101 15.209858 12.674894 16.768702 14.640022], shape=(5,), dtype=float32)
tf.Tensor([14.640022 13.060101 16.768702 12.674894 15.209858], shape=(5,), dtype=float32)


##3.12. Chuyển đổi kiểu dữ liệu

In [13]:
t_float = tf.constant(3.9, tf.float32)
print(t_float,'_ _ _',t_float.dtype)
t_int = tf.cast(t_float, tf.int32)
print(t_int,'_ _ _',t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) _ _ _ <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) _ _ _ <dtype: 'int32'>


##3.13. Các phép toán trong tensorflow

###3.13.1. Tính căn bậc 2 của một tensor scalar

In [14]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


###3.13.2. Cộng 2 tensor

In [16]:
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)
c = tf.add(a, b)
d = a + b
print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


###3.13.3. Nhân 2 tensor

In [17]:
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)
c = tf.multiply(a, b)
d = a * b
print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [19]:
a = tf.constant([6. ,6., 6.])
b = tf.constant([4. ,4., 4.])
c = tf.constant([3. ,3., 3.])
d = tf.add(a,b)
e = tf.add_n([a,b,c])
f = tf.subtract(a,b)
g = tf.multiply(a,b)
h = tf.divide(a,b)
i = tf.scalar_mul(3,a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a,b)
l = tf.negative(a)
print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


##3.14. Các phép toán làm tròn và so sánh

In [20]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


##3.15. Các phép toán trên vector và ma trận

In [21]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


##3.16. Biến trong tensorflow

In [22]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]


In [23]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>


##3.17. Môi trường tính toán Graph trong tensorflow

In [24]:
# Define a Python function.
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# `a_function_that_uses_a_graph` is a TensorFlow `Function`.
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Call a `Function` like a Python function.
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


###3.17.1. Biến một hàm Python thuần túy sang graph

In [25]:
def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# Use the decorator to make `outer_function` a `Function`.
@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return inner_function(x, y, b)

# Note that the callable will create a graph that
# includes `inner_function` as well as `outer_function`.
rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]


##3.18. Modules, Layers và Models

In [26]:
class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.a_variable = tf.Variable(5.0, name="train_me")
    self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

  def __call__(self, x):
    return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")

rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variables', simple_module.trainable_variables)
print('All variables', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


##3.19. Lưu weight

###3.19.1.  Lưu checkpoint

In [28]:
class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.a_variable = tf.Variable(5.0, name="train_me")
    self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

  def __call__(self, x):
    return self.a_variable * x + self.non_trainable_variable

my_model = SimpleModule(name="my_model")

chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

'my_checkpoint'

###3.19.2.  Phục hồi checkpoint

In [30]:
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

# Should be the same result as above
print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor(30.0, shape=(), dtype=float32)
