<a href="https://colab.research.google.com/github/DinhThanh-Dat/ThucHanhDeepLearning/blob/main/Baitaptuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# tao numpy arry
# mang 1 chieu
mylist = [1,2,3,4]
print('Python list',mylist)
numpy_arr = np.array(mylist)
print('Numpy array',numpy_arr)
print('==================\n')

#mang 2 chieu
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)
print('==================\n')

#mang 3 chieu
d=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(d)
print(d.shape)

Python list [1, 2, 3, 4]
Numpy array [1 2 3 4]

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1
e=np.zeros((2,2))
f=np.ones((4,4))
print('Zero: \n',e)
print('One: \n',f)


Zero: 
 [[0. 0.]
 [0. 0.]]
One: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Thay đổi kích thước ma trận
e=np.array([[1,2,3],[4,5,6]])
print(e)

f=e.reshape(3,2)
print('Reshape: \n',f)
print('============\n')
g = np.array([[(1,2,3),(4,5,6)],
             [(7,8,9),(10,11,12)]
             ])
print(g)
print('reshape:\n',g.shape)

h = g.reshape(3,4)
print('reshape(3,4):\n',h)

j = g.reshape(3,2,2)
print('reshape(3,2,2):\n',j)

k=g.reshape(2,3,2)
print('reshape(2,3,2):\n',k)


[[1 2 3]
 [4 5 6]]
Reshape: 
 [[1 2]
 [3 4]
 [5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
reshape:
 (2, 2, 3)
reshape(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape(3,2,2):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
reshape(2,3,2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#chuyển array nhiều chiều về 1 chiều
e=np.array([(1,2,3),(4,5,6)])
f=e.flatten()
print(f)

g=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
j=g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Thêm dòng dữ liệu với hstack và vstack
f=np.array([(1,2,3),(4,5,6)])
g=np.array([(7,8,9),(10,11,12)])
h=np.vstack((f,g))
print('Horizontal Append\n',h)
i=np.hstack((f,g))
print('Vertical Append\n',i)

Horizontal Append
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vertical Append
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


##Sinh mảng số nguyên ngẫu nhiên

In [2]:
import numpy as np
a = np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b = np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c = np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [69 91 38 66 74]
Random 2-D array
 [[33 83 19 51]
 [69 23  4 98]
 [14 40 21 17]]
Random 3-D array
 [[[21 25 48]
  [76 55 59]
  [41 87 14]
  [13 67 74]]

 [[ 3 61 28]
  [27  2 91]
  [ 3 54 84]
  [15 97 74]]

 [[91 43 16]
  [93 66 56]
  [87 77 13]
  [62 59 66]]]


##Sinh mảng số thực trong khoảng [0, 1]

In [3]:
a = np.random.rand(5)
print('Random 1-D array\n',a)
b = np.random.rand(3,4)
print('Random 2-D array\n',b)
c = np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.31792836 0.42082683 0.61340472 0.97502243 0.59683843]
Random 2-D array
 [[0.29476278 0.41576578 0.28837485 0.39984892]
 [0.65343521 0.74220514 0.08314377 0.52393819]
 [0.70957077 0.20180779 0.40804613 0.69971831]]
Random 3-D array
 [[[0.77164265 0.73569035 0.32925238]
  [0.89637054 0.93499516 0.7098429 ]
  [0.07024965 0.55263389 0.11991733]
  [0.15391967 0.0431022  0.22925579]]

 [[0.99734518 0.41614728 0.37595022]
  [0.54451991 0.07175131 0.2240159 ]
  [0.35897071 0.67449539 0.86089888]
  [0.98134568 0.71840127 0.45835358]]

 [[0.98959303 0.15679683 0.66366364]
  [0.22428254 0.29129992 0.48470037]
  [0.74557544 0.85980994 0.30611892]
  [0.56392906 0.21852149 0.98742839]]]
