<a href="https://colab.research.google.com/github/DinhThanh-Dat/ThucHanhDeepLearning/blob/main/Baitaptuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bai Numpy

##3.1. Tạo array 1-chiều, 3.2. 2-chiều, 3.3. 3 chiều

In [ ]:
import numpy as np
# tao numpy arry
# mang 1 chieu
mylist = [1,2,3,4]
print('Python list',mylist)
numpy_arr = np.array(mylist)
print('Numpy array',numpy_arr)
print('==================\n')

#mang 2 chieu
c=np.array([(1,2,3),(4,5,6)]) #2 dòng , 3 cột
print(c)                      # in ra ma trận
print(c.shape)                # in ra hình dạng (dòng, cột)
print(c.dtype)
print('==================\n')

#mang 3 chieu
d=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(d)
print(d.shape)

Python list [1, 2, 3, 4]
Numpy array [1 2 3 4]

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


##3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [ ]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1
e=np.zeros((2,2))
f=np.ones((4,4))
print('Zero: \n',e)
print('One: \n',f)


Zero: 
 [[0. 0.]
 [0. 0.]]
One: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##3.5. Reshape và Flatten ma trận
###3.5.1. Reshape thay đổi kích thước ma trận

In [ ]:
#Thay đổi kích thước ma trận
e=np.array([[1,2,3],[4,5,6]])  # Tạo ma trận e kích thước 2x3
print(e)

f=e.reshape(3,2)               # Thay đổi hình dáng ma trận e từ 2x3 sang ma trận mới f kích thước 3x2
print('Reshape: \n',f)
print('============\n')
g = np.array([[(1,2,3),(4,5,6)],
             [(7,8,9),(10,11,12)]
             ])
print(g)
print('reshape:\n',g.shape)

h = g.reshape(3,4)           # Biến đổi khối g 3 chiều thành ma trận 2 chiều h kích thước 3x4
print('reshape(3,4):\n',h)

j = g.reshape(3,2,2)         # Biến đổi khối g 3 chiều thành ma trận 3 chiều j kích thước 3x2x2
print('reshape(3,2,2):\n',j)

k=g.reshape(2,3,2)           # Biến đổi khối g thành khối k 3 chiều có kích thước mới là (2, 3, 2)
print('reshape(2,3,2):\n',k)


[[1 2 3]
 [4 5 6]]
Reshape: 
 [[1 2]
 [3 4]
 [5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
reshape:
 (2, 2, 3)
reshape(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape(3,2,2):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
reshape(2,3,2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


###3.5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [ ]:
#chuyển array nhiều chiều về 1 chiều
e=np.array([(1,2,3),(4,5,6)]) # Tạo ma trận e kích thước 2x3
f=e.flatten() # Làm phẳng ma trận e (2 chiều) đưa về mảng 1 chiều f liền mạch
print(f)

g=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
j=g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


##3.6. Thêm dòng dữ liệu với hstack và vstack

In [ ]:
import numpy as np
f = np.array([1., 2., 3.])                # Tạo mảng 1 chiều f
g = np.array([4., 5., 6.])                # Tạo mảng 1 chiều g

h_stack = np.hstack((f, g))               # Ghép nối mảng f và g theo trục ngang (kết hợp các cột liên tiếp)
print('Horizontal Append\n', h_stack)     # In kết quả ghép ngang -> Kết quả: [1. 2. 3. 4. 5. 6.]

v_stack = np.vstack((f, g))               # Ghép nối mảng f và g theo trục dọc (xếp g thành dòng phía dưới f)
print('Vertical Append\n', v_stack)       # In kết quả ghép dọc tạo ra ma trận 2x3

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


##3.7. Sinh mảng số ngẫu nhiên
###3.7.1. Sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np
a = np.random.randint(100,size=(5,)) # Sinh ngẫu nhiên mảng 1 chiều gồm 5 số nguyên trong khoảng [0, 100)
print('Random 1-D array\n',a)
b = np.random.randint(100,size=(3,4)) # Sinh ngẫu nhiên ma trận 2 chiều kích thước 3 dòng 4 cột chứa các số nguyên từ 0 đến 99
print('Random 2-D array\n',b)
c = np.random.randint(100,size=(3,4,3)) # Sinh ngẫu nhiên mảng 3 chiều kích thước (3, 4, 3) chứa các số nguyên từ 0 đến 99
print('Random 3-D array\n',c)

Random 1-D array
 [69 91 38 66 74]
Random 2-D array
 [[33 83 19 51]
 [69 23  4 98]
 [14 40 21 17]]
Random 3-D array
 [[[21 25 48]
  [76 55 59]
  [41 87 14]
  [13 67 74]]

 [[ 3 61 28]
  [27  2 91]
  [ 3 54 84]
  [15 97 74]]

 [[91 43 16]
  [93 66 56]
  [87 77 13]
  [62 59 66]]]


##3.7.2. Sinh mảng số thực trong khoảng [0, 1]

In [ ]:
a = np.random.rand(5) # Sinh mảng 1 chiều chứa 5 số thực ngẫu nhiên từ 0 đến 1
print('Random 1-D array\n',a)
b = np.random.rand(3,4)
print('Random 2-D array\n',b)
c = np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.31792836 0.42082683 0.61340472 0.97502243 0.59683843]
Random 2-D array
 [[0.29476278 0.41576578 0.28837485 0.39984892]
 [0.65343521 0.74220514 0.08314377 0.52393819]
 [0.70957077 0.20180779 0.40804613 0.69971831]]
Random 3-D array
 [[[0.77164265 0.73569035 0.32925238]
  [0.89637054 0.93499516 0.7098429 ]
  [0.07024965 0.55263389 0.11991733]
  [0.15391967 0.0431022  0.22925579]]

 [[0.99734518 0.41614728 0.37595022]
  [0.54451991 0.07175131 0.2240159 ]
  [0.35897071 0.67449539 0.86089888]
  [0.98134568 0.71840127 0.45835358]]

 [[0.98959303 0.15679683 0.66366364]
  [0.22428254 0.29129992 0.48470037]
  [0.74557544 0.85980994 0.30611892]
  [0.56392906 0.21852149 0.98742839]]]


###3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
a = np.random.normal(5,0.5,10) # Sinh mảng 10 phần tử ngẫu nhiên theo phân phối chuẩn với Trung bình = 5 và Độ lệch chuẩn = 0.5
print(a)

[4.41723719 5.72652408 4.35549481 4.83435475 5.08017554 5.31240972
 5.3565249  4.66766965 4.85726617 4.85193152]


###3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)

b = np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)

8
[[12 18  2  8 16]
 [12 10 10 20  6]
 [ 8 16 10  8  8]]


##3.8. Thay đổi giá trị của ma trận

In [ ]:
A = np.matrix(np.ones((5,5)))
print('The matrix\n',A)
np.array(A)[2] = 2 # np.array tạo ra một bản sao (copy) vùng nhớ mới nên không tác động trực tiếp thay đổi lên ma trận gốc A
print('Change values of third row with array\n',A)
np.asarray(A)[2] = 2 # np.asarray tham chiếu và chia sẻ chung vùng nhớ với ma trận gốc A nên thay đổi sẽ tác động trực tiếp
print('Change values of third row with asarray\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##3.9. Sinh dãy số theo khoảng cho trước
###3.9.1. Dùng hàm arange

In [ ]:
#tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1,20)
print(a)

#tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1,20,2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


###3.9.2. Dùng hàm linspace

In [ ]:
a = np.linspace(1,5,num=10) # Chia đều khoảng từ 1.0 đến 5.0 thành đúng 10 phần tử có khoảng cách bằng nhau
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


##3.10. Index và slice

In [ ]:
#slide
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:',a[0])
print('second row:',a[1])

#indexing
# Kỹ thuật Indexing nâng cao: dấu ":" đại diện lấy toàn bộ dòng
print('second column:',a[:,1])
print('first column:',a[:,0])
print('First two values of second row:', a[1,:2])



[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


#Bai PANDAS
##Series là cấu trúc dữ liệu 1-chiều.

In [ ]:
import pandas as pd
#Tao pandas series tư list
a = pd.Series([1,2,3])
print(a)
print('First value:', a[0])
b = pd.Series([1,2,3],index=['a','b','c'])
print(b)
print('First value:',b['a'])
#Tao pandas series tu dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1
1    2
2    3
dtype: int64
First value: 1
a    1
b    2
c    3
dtype: int64
First value: 1
day1    420
day2    380
day3    390
dtype: int64


##TẠO ĐỐI TƯỢNG DATAFRAME
###DataFrame là mảng 2-chiều có nhãn ở 2 trục

In [ ]:
h = np.array([[1,2],[3,4]])
df_h = pd.DataFrame(h)
print('DataFrame\n',df_h)

numpy_h = np.array(df_h) # Chuyển đổi dữ liệu ngược lại từ bảng Pandas --> về mảng Numpy
print('Munpy array:\n',numpy_h)

DataFrame
    0  1
0  1  2
1  3  4
Munpy array:
 [[1 2]
 [3 4]]


###Tạo DataFrame mảng 2-chiều có tên cột

In [ ]:
dic = {'Name':['John', 'Smith'],'Age':[30,40]} # Khai báo từ điển với tên cột và mảng giá trị của cột đó
df = pd.DataFrame(dic) # Tạo bảng DataFrame từ bộ từ điển dic
print(df)

#tao mang 20 x 4
r = np.random.randn(20,4) # Sinh mảng ngẫu nhiên kích thước 20 dòng, 4 cột theo phân phối chuẩn
df = pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head()) # in 5 dong dau tien
#


    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0 -0.596673  0.717880  0.473530 -0.665171
1  0.913026 -1.400002 -1.123679 -0.961991
2 -0.862822 -0.226439 -1.181613 -0.139259
3 -0.836565 -0.178001 -0.668313 -0.656787
4 -0.559978  2.210645  0.646549 -0.009999


###Slice DataFrame

In [ ]:
#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  #in 5 dòng đầu tiên

#chọn 1 cột
print('Chọn cột so1\n', df['so1'])

#chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

#chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

#chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

#Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -1.067409  0.244046  1.176908  0.023624
1 -0.244754  1.081917  1.216733 -1.706044
2 -1.366678  1.610019  0.649939  0.116620
3  2.040210  0.551901 -0.058917  1.289878
4 -0.150427 -0.080637  0.660934 -2.036406
Chọn cột so1
 0    -1.067409
1    -0.244754
2    -1.366678
3     2.040210
4    -0.150427
5    -0.115337
6    -0.179948
7    -1.141463
8     1.077770
9     0.651259
10   -0.763751
11    1.022841
12   -0.944834
13    1.064817
14    0.014561
15    1.933591
16    0.642434
17   -0.784759
18   -1.617846
19   -1.091596
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -1.067409  0.244046  1.176908  0.023624
1 -0.244754  1.081917  1.216733 -1.706044
2 -1.366678  1.610019  0.649939  0.116620
Chọn nhiều cột
          so1       so3
0  -1.067409  1.176908
1  -0.244754  1.216733
2  -1.366678  0.649939
3   2.040210 -0.058917
4  -0.150427  0.660934
5  -0.115337 -0.103147
6  -0.179948 -0.597528
7  -1.141463  0.012153


##7.1. Nối nhiều DataFrame

In [ ]:
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])

df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

#Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

#Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


##7.2. Đọc dữ liệu từ CSV

In [ ]:
# Đọc dữ liệu từ CSV
path = '/content/sample_data/Salary_Data.csv'
COLUMNS = ['YearsExperience', 'Salary']

df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)

df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

##7.3. Gom nhóm dữ liệu DataFrame

In [ ]:
#Gom nhóm dữ liệu trong DataFrame
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())

print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

##8. BÀI TẬP

1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [ ]:
import numpy as np

arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng được tạo ngẫu nhiên:")
print(arr)

check_all_nonzero = np.all(arr)

print("\nTất cả các phần tử có khác 0 không?")
if check_all_nonzero:
    print("Có, tất cả các phần tử đều khác 0.")
else:
    print("Không, trong mảng có ít nhất một phần tử bằng 0.")

Mảng được tạo ngẫu nhiên:
[[16  9  9]
 [11  6  4]
 [ 2 14 14]]

Tất cả các phần tử có khác 0 không?
Có, tất cả các phần tử đều khác 0.


2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [ ]:
import numpy as np

# 1. Tạo mảng ngẫu nhiên kích thước 3x3 với giá trị trong khoảng [0, 20]
# Để bao gồm cả số 20, ta đặt tham số high là 21
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng được tạo ngẫu nhiên:")
print(arr)

# 2. Kiểm tra xem có tồn tại ít nhất một phần tử khác 0 hay không
# Cách 1: Sử dụng trực tiếp mảng (0 là False, khác 0 là True)
has_nonzero = np.any(arr)

# Cách 2: Viết điều kiện rõ ràng để dễ đọc
# has_nonzero = np.any(arr != 0)

print("\nCó tồn tại phần tử nào khác 0 trong mảng không?")
if has_nonzero:
    print("Có, tồn tại ít nhất một phần tử khác 0.")
else:
    print("Không, tất cả các phần tử trong mảng đều bằng 0.")

Mảng được tạo ngẫu nhiên:
[[ 9  0 19]
 [ 2  8 20]
 [ 0 15 13]]

Có tồn tại phần tử nào khác 0 trong mảng không?
Có, tồn tại ít nhất một phần tử khác 0.


3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [ ]:
import numpy as np

# --- 1. SO SÁNH MẢNG 1 CHIỀU ---
print("--- So sánh mảng 1 chiều ---")
a1 = np.array([10, 20, 30])
b1 = np.array([15, 20, 25])

print(f"Mảng a1: {a1}")
print(f"Mảng b1: {b1}")

print("a1 > b1  (greater):      ", np.greater(a1, b1))
print("a1 >= b1 (greater_equal):", np.greater_equal(a1, b1))
print("a1 < b1  (less):         ", np.less(a1, b1))
print("a1 <= b1 (less_equal):   ", np.less_equal(a1, b1))

print("\n" + "-"*30 + "\n")

# --- 2. SO SÁNH MẢNG 2 CHIỀU ---
print("--- So sánh mảng 2 chiều ---")
a2 = np.array([[1, 5],
               [8, 12]])

b2 = np.array([[2, 4],
               [8, 10]])

print("Ma trận a2:\n", a2)
print("Ma trận b2:\n", b2)

# Thực hiện so sánh
print("\na2 > b2 (Greater):\n", np.greater(a2, b2))
print("\na2 >= b2 (Greater Equal):\n", np.greater_equal(a2, b2))
print("\na2 < b2 (Less):\n", np.less(a2, b2))
print("\na2 <= b2 (Less Equal):\n", np.less_equal(a2, b2))

--- So sánh mảng 1 chiều ---
Mảng a1: [10 20 30]
Mảng b1: [15 20 25]
a1 > b1  (greater):       [False False  True]
a1 >= b1 (greater_equal): [False  True  True]
a1 < b1  (less):          [ True False False]
a1 <= b1 (less_equal):    [ True  True False]

------------------------------

--- So sánh mảng 2 chiều ---
Ma trận a2:
 [[ 1  5]
 [ 8 12]]
Ma trận b2:
 [[ 2  4]
 [ 8 10]]

a2 > b2 (Greater):
 [[False  True]
 [False  True]]

a2 >= b2 (Greater Equal):
 [[False  True]
 [ True  True]]

a2 < b2 (Less):
 [[ True False]
 [False False]]

a2 <= b2 (Less Equal):
 [[ True False]
 [ True False]]


4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [ ]:
import numpy as np

# 1. Tạo 10 số 0
zeros = np.zeros(10)

# 2. Tạo 10 số 1
ones = np.ones(10)

# 3. Tạo 10 số 5
# (Tạo mảng 10 số 1 rồi nhân với 5)
fives = np.ones(10) * 5

# 4. Kết hợp các mảng lại với nhau
result = np.concatenate([ones, zeros, fives])

print("Mảng kết quả:")
print(result)

# Kiểm tra kích thước mảng
print("\nKích thước mảng:", result.size)

Mảng kết quả:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]

Kích thước mảng: 30


5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [ ]:

# Sử dụng np.arange(start, stop, step)
# start = 30 (bắt đầu từ 30)
# stop  = 71 (để bao gồm cả số 70, vì tham số stop không lấy giá trị cuối)
# step  = 2  (bước nhảy là 2 để lấy các số chẵn)

arr_even = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(arr_even)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
(Tìm hiểu hàm identity của numpy)

In [ ]:
# Sử dụng np.identity(n) để tạo ma trận đơn vị kích thước n x n
# n = 3 cho ma trận 3x3
matrix_identity = np.identity(3)

print("Ma trận đơn vị 3x3 (sử dụng np.identity):")
print(matrix_identity)

# Cách khác: Sử dụng np.eye(N, M)
# (np.eye linh hoạt hơn vì có thể tạo ma trận không vuông)
matrix_eye = np.eye(3)

print("\nMa trận đơn vị 3x3 (sử dụng np.eye):")
print(matrix_eye)

Ma trận đơn vị 3x3 (sử dụng np.identity):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Ma trận đơn vị 3x3 (sử dụng np.eye):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử
đầu và cuối

In [ ]:
# 1. Tạo mảng trong khoảng [15, 55]
# Dùng np.arange(15, 56) để bao gồm cả số 55
# Ở đây tôi tạo mảng đầy đủ rồi lấy 10 phần tử đầu tiên để đúng yêu cầu "10 phần tử"
# Hoặc dùng np.linspace nếu bạn muốn 10 phần tử cách đều nhau trong khoảng đó.

arr = np.arange(15, 25) # Ví dụ tạo 10 phần tử từ 15 đến 24
# Hoặc: arr = np.linspace(15, 55, 10) # Tạo chính xác 10 số từ 15 đến 55

print("Mảng ban đầu (10 phần tử):")
print(arr)

# 2. In các giá trị ngoại trừ phần tử đầu và cuối
# Sử dụng slicing [1:-1]
# 1: Bắt đầu từ index 1 (phần tử thứ hai)
# -1: Dừng lại trước index cuối cùng
result = arr[1:-1]

print("\nCác giá trị ngoại trừ phần tử đầu và cuối:")
print(result)

Mảng ban đầu (10 phần tử):
[15 16 17 18 19 20 21 22 23 24]

Các giá trị ngoại trừ phần tử đầu và cuối:
[16 17 18 19 20 21 22 23]


8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong
khoảng [9, 15]

In [ ]:
# 1. Tạo mảng 20 phần tử trong khoảng [0, 20]
# Sử dụng np.linspace để lấy đúng 20 số cách đều nhau từ 0 đến 20
arr = np.linspace(0, 20, 20)

print("Mảng ban đầu:")
print(arr)

# 2. Đổi dấu các số nằm trong khoảng [9, 15]
# Tạo một mặt nạ điều kiện (mask): (arr >= 9) VÀ (arr <= 15)
condition = (arr >= 9) & (arr <= 15)

# Đổi dấu trực tiếp bằng cách nhân với -1 tại các vị trí thỏa mãn điều kiện
arr[condition] *= -1

print("\nMảng sau khi đổi dấu các phần tử trong khoảng [9, 15]:")
print(arr)

Mảng ban đầu:
[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]

Mảng sau khi đổi dấu các phần tử trong khoảng [9, 15]:
[  0.           1.05263158   2.10526316   3.15789474   4.21052632
   5.26315789   6.31578947   7.36842105   8.42105263  -9.47368421
 -10.52631579 -11.57894737 -12.63157895 -13.68421053 -14.73684211
  15.78947368  16.84210526  17.89473684  18.94736842  20.        ]


9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]

In [ ]:
# Sử dụng np.random.randint(low, high, size)
# low = 10 (giá trị nhỏ nhất có thể nhận)
# high = 22 (giá trị biên trên, vì NumPy không lấy giá trị này, nên dùng 22 để có thể xuất hiện số 21)
# size = (3, 4) (kích thước ma trận: 3 hàng, 4 cột)

matrix = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3x4 với các giá trị từ 10 đến 21:")
print(matrix)

Ma trận 3x4 với các giá trị từ 10 đến 21:
[[17 12 13 11]
 [12 14 16 17]
 [17 19 12 12]]


10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có
giá trị 0

In [ ]:
# 1. Tạo ma trận 10x10 toàn số 1
matrix = np.ones((10, 10))

# 2. Thay thế các phần tử bên trong thành số 0
# Slicing [1:-1, 1:-1] có nghĩa là:
# - Về hàng: lấy từ hàng index 1 đến hàng sát cuối (bỏ hàng đầu và cuối)
# - Về cột: lấy từ cột index 1 đến cột sát cuối (bỏ cột đầu và cuối)
matrix[1:-1, 1:-1] = 0

print("Ma trận 10x10 với biên là 1 và bên trong là 0:")
print(matrix)

Ma trận 10x10 với biên là 1 và bên trong là 0:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu
hàm diag của numpy)

In [ ]:
# 1. Tạo danh sách các giá trị muốn đặt trên đường chéo chính
values = [1, 2, 3, 4, 5]

# 2. Sử dụng np.diag để tạo ma trận 5x5 từ danh sách trên
# Các phần tử không nằm trên đường chéo chính sẽ tự động bằng 0
matrix_diag = np.diag(values)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(matrix_diag)

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum
của numpy)

In [ ]:
# 1. Tạo mảng 3x3x3 với các số nguyên ngẫu nhiên từ 1 đến 10
arr_3d = np.random.randint(1, 11, size=(3, 3, 3))

print("Mảng 3x3x3 được tạo ra:")
print(arr_3d)

# 2. Tính tổng theo mỗi dòng (axis=1)
# Kết quả sẽ là tổng của các hàng trong từng ma trận con
sum_rows = np.sum(arr_3d, axis=1)

# 3. Tính tổng theo mỗi cột (axis=2)
# Kết quả sẽ là tổng của các cột trong từng ma trận con
sum_cols = np.sum(arr_3d, axis=2)

print("\n--- KẾT QUẢ TÍNH TOÁN ---")
print("Tổng theo mỗi dòng (kết quả mỗi tầng là một mảng 1x3):")
print(sum_rows)

print("\nTổng theo mỗi cột (kết quả mỗi tầng là một mảng 1x3):")
print(sum_cols)

Mảng 3x3x3 được tạo ra:
[[[ 7  3  2]
  [10  6 10]
  [ 9  8  1]]

 [[ 3  6  2]
  [ 8  6  3]
  [ 4  6  7]]

 [[ 5  7  7]
  [ 2  1 10]
  [ 8  9  2]]]

--- KẾT QUẢ TÍNH TOÁN ---
Tổng theo mỗi dòng (kết quả mỗi tầng là một mảng 1x3):
[[26 17 13]
 [15 18 12]
 [15 17 19]]

Tổng theo mỗi cột (kết quả mỗi tầng là một mảng 1x3):
[[12 26 18]
 [11 17 17]
 [19 13 19]]


13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)

In [ ]:
import numpy as np

# Tạo 2 vector ngẫu nhiên 10 phần tử
v1 = np.random.rand(10)
v2 = np.random.rand(10)

# Thực hiện inner product bằng np.dot
inner_product = np.dot(v1, v2)

print("Vector 1:", v1)
print("Vector 2:", v2)
print("Kết quả Inner Product:", inner_product)

Vector 1: [0.90222381 0.7729562  0.74751603 0.6673634  0.23336881 0.63432748
 0.62983321 0.5302945  0.4675458  0.89012088]
Vector 2: [0.77932635 0.86444128 0.17743737 0.9161779  0.91629934 0.8167955
 0.49005562 0.89907893 0.09558142 0.42841198]
Kết quả Inner Product: 4.058771480533601


14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của
ma trận A

In [ ]:
# Tạo ma trận A kích thước 4x3
A = np.random.randint(1, 10, size=(4, 3))

# Tạo vector y gồm 3 phần tử (khớp với số cột của A)
y = np.array([10, 20, 30])

# Thêm y vào từng dòng của A
result = A + y

print("Ma trận A:\n", A)
print("\nVector y:", y)
print("\nKết quả sau khi cộng:\n", result)

Ma trận A:
 [[3 9 9]
 [2 9 8]
 [1 8 9]
 [6 6 4]]

Vector y: [10 20 30]

Kết quả sau khi cộng:
 [[13 29 39]
 [12 29 38]
 [11 28 39]
 [16 26 34]]


15. Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
import pandas as pd

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


16. Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series (Tìm hiểu thuộc tính ix của
pandas)

In [ ]:
# Tạo một DataFrame mẫu
data = {'Cột 1': [10, 20, 30], 'Cột 2': [40, 50, 60]}
df = pd.DataFrame(data)

# Cách 1: Sử dụng .iloc (Khuyên dùng thay cho .ix)
# iloc[:, 0] nghĩa là lấy tất cả các dòng của cột index 0
series_from_col = df.iloc[:, 0]

# Cách 2: Truy cập theo tên trực tiếp
# series_from_col = df['Cột 1']

print("DataFrame ban đầu:\n", df)
print("\nCột đầu tiên dưới dạng Series:\n", series_from_col)
print("Kiểu dữ liệu:", type(series_from_col))

DataFrame ban đầu:
    Cột 1  Cột 2
0     10     40
1     20     50
2     30     60

Cột đầu tiên dưới dạng Series:
 0    10
1    20
2    30
Name: Cột 1, dtype: int64
Kiểu dữ liệu: <class 'pandas.core.series.Series'>


17. Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên

In [ ]:
# Tạo DataFrame 4x3 với các số nguyên ngẫu nhiên từ 1 đến 100
# Đặt tên cột là 'Col_1', 'Col_2', 'Col_3' để dễ quan sát
df = pd.DataFrame(np.random.randint(1, 101, size=(4, 3)),
                  columns=['Col_1', 'Col_2', 'Col_3'])

print("DataFrame ban đầu:")
print(df)

# Sắp xếp DataFrame theo giá trị của 'Col_1' tăng dần
df_sorted = df.sort_values(by='Col_1')

print("\nDataFrame sau khi sắp xếp theo 'Col_1':")
print(df_sorted)

DataFrame ban đầu:
   Col_1  Col_2  Col_3
0     74     52     97
1     50     49     56
2     21     56     95
3     39     63     44

DataFrame sau khi sắp xếp theo 'Col_1':
   Col_1  Col_2  Col_3
2     21     56     95
3     39     63     44
1     50     49     56
0     74     52     97


18. Viết chương trình Pandas thay đổi index của một Series (dùng pandas.reindex)

In [ ]:
# Tạo Series ban đầu giống trong hình
data = [1, 2, 3, 4, 5]
idx = ['A', 'B', 'C', 'D', 'E']
ds = pd.Series(data, index=idx)

print("Original Data Series:")
print(ds)

# Thay đổi thứ tự index bằng reindex
# Ở đây ta đổi chỗ B lên trước A
new_idx = ['B', 'A', 'C', 'D', 'E']
ds_new = ds.reindex(index=new_idx)

print("\nData Series after changing the order of index:")
print(ds_new)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64

Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


19. Viết chương trình Pandas tìm những phần tử trong Series x mà không có trong Series y (Tìm
hiểu hàm isin của pandas)

In [ ]:
# Tạo 2 Series như đề bài
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

# Sử dụng ~ kết hợp với isin để lọc
# sr1.isin(sr2) trả về True cho [2, 4]
# ~sr1.isin(sr2) trả về True cho [1, 3, 5]
result = sr1[~sr1.isin(sr2)]

print("sr1:")
print(sr1)
print("\nsr2:")
print(sr2)
print("\nItems of sr1 not present in sr2:")
print(result)

sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64

sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


20. Tìm hiểu phép toán numpy.union1d, numpy.intersect1d (hội, giao) và viết chương trình minh
họa 2 hàm này trên 2 Series x, y ngẫu nhiên có 20 phần tử

In [ ]:

x = pd.Series(np.random.randint(0, 31, 20))
y = pd.Series(np.random.randint(0, 31, 20))


intersection = np.intersect1d(x, y)


union = np.union1d(x, y)

print("Series x (20 phần tử):", x.values)
print("Series y (20 phần tử):", y.values)

print("\n--- KẾT QUẢ ---")
print("Giao (Phần tử chung):", intersection)
print("Hội (Tất cả phần tử không trùng lặp):", union)

Series x (20 phần tử): [27 15 25 11 27 25 25 18 27  5 23 22 17 16  1 26  5  1  6  1]
Series y (20 phần tử): [ 6 26  8  0  8 17 29  2  9 23 10 22 18 22 20  2 26 18 18 21]

--- KẾT QUẢ ---
Giao (Phần tử chung): [ 6 17 18 22 23 26]
Hội (Tất cả phần tử không trùng lặp): [ 0  1  2  5  6  8  9 10 11 15 16 17 18 20 21 22 23 25 26 27 29]


21.Viết chương trình Pandas thêm series y vào series x theo chiều dọc (vertical), chiều ngang
(horizontal) (Tìm hiểu hàm append và concat của pandas).................

In [ ]:
import pandas as pd

# Khởi tạo hai series theo mẫu
x = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'])

# Thêm theo chiều dọc (vertical) dùng pd.concat (trục axis=0)
chiều_dọc = pd.concat([x, y], axis=0, ignore_index=True)

# Thêm theo chiều ngang (horizontal) dùng pd.concat (trục axis=1)
chiều_ngang = pd.concat([x, y], axis=1)

print("Thêm theo chiều dọc:\n", chiều_dọc)
print("\nThêm theo chiều ngang:\n", chiều_ngang)

Thêm theo chiều dọc:
 0     0
1     1
2     2
3     3
4     4
5     5
6     6
7     7
8     8
9     9
10    p
11    q
12    r
13    s
14    t
15    u
16    v
17    w
18    x
19    y
dtype: object

Thêm theo chiều ngang:
    0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


22. Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame sau
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
import numpy as np
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Câu 22: Tạo và hiển thị dữ liệu DataFrame
df = pd.DataFrame(exam_data, index=labels)
print("--- Câu 22: DataFrame ban đầu ---")
print(df)

--- Câu 22: DataFrame ban đầu ---
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


23. Từ bài 22, cho biết 3 dòng đầu tiên

In [ ]:
print("\n--- Câu 23: 3 dòng đầu tiên ---")
print(df.head(3))
# Hoặc có thể sử dụng slice: print(df.iloc[:3])


--- Câu 23: 3 dòng đầu tiên ---
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


24. Từ bài 22, chọn cột ‘name’ và ‘score’


In [ ]:
print("\n--- Câu 24: Chọn cột 'name' và 'score' ---")
print(df[['name', 'score']])


--- Câu 24: Chọn cột 'name' và 'score' ---
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


25. Từ bài 22, chọn những dòng có attemps > 2

In [ ]:
print("\n--- Câu 25: Các dòng có attempts > 2 ---")
print(df[df['attempts'] > 2])


--- Câu 25: Các dòng có attempts > 2 ---
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


26. Từ bài 22, cho biết số dòng, số cột của DataFram

In [ ]:
print("\n--- Câu 26: Kích thước của DataFrame ---")
so_dong, so_cot = df.shape
print(f"Số dòng: {so_dong}, Số cột: {so_cot}")


--- Câu 26: Kích thước của DataFrame ---
Số dòng: 10, Số cột: 4


27. Từ bài 22, cho biết những dòng có score là NaN (tìm hiểu hàm isnull của pandas)

In [ ]:
print("\n--- Câu 27: Các dòng có score là NaN ---")
print(df[df['score'].isnull()])


--- Câu 27: Các dòng có score là NaN ---
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


28. Từ bài 22, cho biết những dòng có score trong khoảng (15, 20) (tìm hiểu hàm between của
pandas)

In [ ]:
print("\n--- Câu 28: Các dòng có score trong khoảng (15, 20) ---")
# Hàm between mặc định bao gồm cả giá trị biên [inclusive=True]
print(df[df['score'].between(15, 20)])


--- Câu 28: Các dòng có score trong khoảng (15, 20) ---
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


29. Từ bài 22, cho biết những dòng có attempt > 2 và score trong khoảng (15, 20)

In [ ]:
print("\n--- Câu 29: Các dòng có attempt > 2 và score trong khoảng (15, 20) ---")
dieu_kien = (df['attempts'] > 2) & (df['score'].between(15, 20))
print(df[dieu_kien])


--- Câu 29: Các dòng có attempt > 2 và score trong khoảng (15, 20) ---
      name  score  attempts qualify
f  Michael   20.0         3     yes


30. Từ bài 22, cho biết những thay đổi giá trị dòng ‘d’, cột score là 19 (tìm hiểu hàm loc của pandas)

In [ ]:
print("\n--- Câu 30: Thay đổi giá trị tại dòng 'd', cột score thành 19 ---")
df.loc['d', 'score'] = 19
print(df)


--- Câu 30: Thay đổi giá trị tại dòng 'd', cột score thành 19 ---
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


Tensor là một vector hay ma trận n-chiều biểu diễn cho tất cả các kiểu dữ liệu.
- Tất cả giá trị trong một tensor có cùng kiểu dữ liệu còn gọi là shape.
- Shape của dữ liệu là chiều của ma trận hoặc mảng (array).
- Tensorflow là 1 framework xử lý các tensor.
- Tất cả các tính toán đều được thực hiện trên graph
- Graph là tập các phép toán được thực hiện liên tục.
- Mỗi phép toán được gọi là 1 opnode và có liên kết với nhau

#Bai TENSORFLOW
3.1. Tensor 0-chiều

Tensor 0-chiều gọi là scalar chỉ chứa 1 giá trị và không có trục.

Ví dụ: tạo một tensor scalar có giá trị là 4

In [ ]:
import tensorflow as tf

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:

rank_0_tensor = tf.constant(4) #Khởi tạo một hằng số tensor 0-chiều (số vô hướng) chứa giá trị nguyên là 4.
                               # Mặc định TensorFlow sẽ tự nhận diện đây là kiểu số nguyên 32-bit (int32).
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)  #Khởi tạo một hằng số tensor chứa duy nhất giá trị là 9.
print(r1)

r1_float = tf.constant(1.12, tf.float32) ##Khởi tạo một hằng số tensor chứa giá trị số thực là 1.12.
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string) ##Khởi tạo một hằng số tensor chứa một chuỗi ký tự (text) là 'Hello Vanlang University'.
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


##3.2.Tensor 1-chiều

In [ ]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0]) #Khởi tạo một hằng số tensor 1-chiều (Vector) từ một danh sách (list) gồm 3 số thực.
                                             #Vì các số được viết dưới dạng số thập phân (2.0, 3.0, 4.0) nên TensorFlow sẽ tự động nhận diện kiểu dữ liệu là số thực
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


##3.3. Tensor 2-chiều (ma trận)

In [ ]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


##3.4. Tensor n-chiều (nhiều trục)

In [ ]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


##3.5.Thuộc tính của tensor

Một tensor gồm có 3 thuộc tính:
- Label (name)
- Dimension (shape)
- Data type (dtype)

In [ ]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


##3.6.Tạo tensor tự động gán giá trị 0 ban đầu

In [ ]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


##3.7.Tạo tensor tự động gán giá trị 1 ban đầu

In [ ]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


##3.8.Tạo tensor tự động với giá trị bất kỳ
Tạo tensor 1-chiều có 3 phần tử có giá trị 10

In [ ]:
t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


##3.9.Tạo tensor 1-chiều với hàm linspace

Hàm linspace tạo một tensor với số phần tử mong muốn trong một phạm vi nhất định

In [ ]:
lin_tensor = tf.linspace(5.0, 20.0, 5) #Khởi tạo một tensor 1-chiều (Vector) bằng cách chia đều khoảng từ 5.0 đến 20.0 thành đúng 5 phần tử
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


##3.10. Tạo tensor 1-chiều với hàm range
Hàm range tạo một tensor với số phần tử không được khai báo. Số phần tử sẽ được hàm tính bằng cách
cộng thêm giá trị delta.

In [ ]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

#Code trên tạo một tensor trong khoảng [3.0, 7.0), mỗi giá trị mới cộng thêm delta=0.5
range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


##3.11. Tạo tensor với giá trị ngẫu nhiên

tạo tensor ngẫu nhiên với hàm random.normal

In [ ]:

range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([ 0.0124386   0.36191794  2.1731014  -0.07258418 -1.8270957 ], shape=(5,), dtype=float32)


In [ ]:
range_tensor = tf.random.normal([3,3])
print(range_tensor)

tf.Tensor(
[[-1.0205067  -1.1185253  -1.2075816 ]
 [-0.55726933 -1.122265    0.28871188]
 [-1.2576934   0.22089222 -0.25129813]], shape=(3, 3), dtype=float32)


 tensor ngẫu nhiên với hàm random.truncated_normal

In [ ]:
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

tf.Tensor([-0.93959117  0.39430243  0.12316041  1.5699466  -1.5486352 ], shape=(5,), dtype=float32)


In [ ]:
range_tensor = tf.random.truncated_normal([3,2])
print(range_tensor)

tf.Tensor(
[[ 0.8625798   0.7930207 ]
 [ 0.17993836 -1.0879866 ]
 [ 0.6434537  -0.42851788]], shape=(3, 2), dtype=float32)


In [ ]:
range_tensor = tf.random.truncated_normal([3,2,2])
print(range_tensor)

tf.Tensor(
[[[-0.42471096  0.7891487 ]
  [-0.19770432 -0.8180212 ]]

 [[-0.8681521   1.4222351 ]
  [ 0.2336684  -0.93629515]]

 [[ 0.21124974  1.5728701 ]
  [ 0.8325392  -0.20229524]]], shape=(3, 2, 2), dtype=float32)


 tạo tensor ngẫu nhiên với hàm random.uniform

In [ ]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor([17.785587 18.954676 14.593812 19.912828 15.219727], shape=(5,), dtype=float32)


In [ ]:
range_tensor = tf.random.uniform([3,2], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[19.139206 19.415966]
 [13.522148 18.77469 ]
 [12.214283 11.987299]], shape=(3, 2), dtype=float32)


In [ ]:
range_tensor = tf.random.uniform([3,2,5], minval=10, maxval=20)
print(range_tensor)


tf.Tensor(
[[[11.6266775 17.107124  10.520012  17.624289  17.247303 ]
  [14.456409  16.583931  13.615881  18.752556  11.384245 ]]

 [[15.991287  18.135872  10.730601  14.688929  10.047818 ]
  [15.848702  10.764545  19.738367  10.0960865 15.554109 ]]

 [[13.6413    11.904941  11.458679  10.305466  18.4976   ]
  [18.989958  10.50029   10.9768505 13.515147  18.191807 ]]], shape=(3, 2, 5), dtype=float32)


tạo tensor ngẫu nhiên với hàm random.uniform và dùng shuffle để xáo trộn giá trị trong tensor

In [ ]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([13.060101 15.209858 12.674894 16.768702 14.640022], shape=(5,), dtype=float32)
tf.Tensor([14.640022 13.060101 16.768702 12.674894 15.209858], shape=(5,), dtype=float32)


##3.12. Chuyển đổi kiểu dữ liệu

Để chuyển từ kiểu dữ liệu này sang kiểu khác ta dùng hàm tf.cast

In [ ]:
t_float = tf.constant(3.9, tf.float32)
print(t_float,'_ _ _',t_float.dtype)
t_int = tf.cast(t_float, tf.int32)
print(t_int,'_ _ _',t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) _ _ _ <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) _ _ _ <dtype: 'int32'>


##3.13. Các phép toán trong tensorflow

###3.13.1. Tính căn bậc 2 của một tensor scalar

In [ ]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


###3.13.2. Cộng 2 tensor

In [ ]:
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)
c = tf.add(a, b)
d = a + b
print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


###3.13.3. Nhân 2 tensor

In [ ]:
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)
c = tf.multiply(a, b)
d = a * b
print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [ ]:
a = tf.constant([6. ,6., 6.])
b = tf.constant([4. ,4., 4.])
c = tf.constant([3. ,3., 3.])
d = tf.add(a,b)
e = tf.add_n([a,b,c])
f = tf.subtract(a,b)
g = tf.multiply(a,b)
h = tf.divide(a,b)
i = tf.scalar_mul(3,a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a,b)
l = tf.negative(a)
print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


##3.14. Các phép toán làm tròn và so sánh

In [ ]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


##3.15. Các phép toán trên vector và ma trận

In [ ]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


##3.16. Biến trong tensorflow

In [ ]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]


In [ ]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>


##3.17. Môi trường tính toán Graph trong tensorflow

In [ ]:

def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x


a_function_that_uses_a_graph = tf.function(a_regular_function)


x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()

tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


###3.17.1. Biến một hàm Python thuần túy sang graph

In [ ]:
def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x


@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return inner_function(x, y, b)


rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]


##3.18. Modules, Layers và Models

In [ ]:
class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.a_variable = tf.Variable(5.0, name="train_me")
    self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

  def __call__(self, x):
    return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")

rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variables', simple_module.trainable_variables)
print('All variables', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


##3.19. Lưu weight

###3.19.1.  Lưu checkpoint

In [ ]:
class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.a_variable = tf.Variable(5.0, name="train_me")
    self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

  def __call__(self, x):
    return self.a_variable * x + self.non_trainable_variable

my_model = SimpleModule(name="my_model")

chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

'my_checkpoint'

###3.19.2.  Phục hồi checkpoint

In [ ]:
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")


print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor(30.0, shape=(), dtype=float32)


# BÀI TẬP

1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [ ]:
import tensorflow as tf

# Tạo tensor kích thước [2, 3] toàn số 0
t1 = tf.zeros([2, 3])
print("Bài 1:\n", t1)

Bài 1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


2. Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được
gán 0

In [ ]:
X = [[1, 2, 3], [4, 5, 6]]
# Tạo tensor cùng shape và dtype với X nhưng toàn số 0
t2 = tf.zeros_like(X)
print("Bài 2:\n", t2)

Bài 2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5

In [ ]:
# Tạo tensor [3, 2] toàn số 5
t3 = tf.fill([3, 2], 5)
print("Bài 3:\n", t3)

Bài 3:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [ ]:
# Cách 1: Lấy 50 số cách đều nhau (số thực)
t4 = tf.linspace(6.0, 10.0, 50)
print("Bài 4:\n", t4)

Bài 4:
 tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)


5. Tạo một tensor 1-chiều có giá trị như [10, 12, 14, …, 100]

In [ ]:
# [10, 12, ..., 100] -> start=10, limit=101 (để lấy cả 100), delta=2
t5 = tf.range(start=10, limit=101, delta=2)
print("Bài 5:\n", t5)

Bài 5:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


6. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối normal với mean=0,
standard deviation = 2

In [ ]:
# mean=0, stddev=2
t6 = tf.random.normal([3, 2], mean=0, stddev=2)
print("Bài 6:\n", t6)

Bài 6:
 tf.Tensor(
[[-0.58035207 -0.79552937]
 [ 1.8033139  -1.0842161 ]
 [-1.4149375   4.259826  ]], shape=(3, 2), dtype=float32)


7. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi
[0, 2]

In [ ]:
# Khoảng [0, 2]
t7 = tf.random.uniform([3, 2], minval=0, maxval=2)
print("Bài 7:\n", t7)

Bài 7:
 tf.Tensor(
[[0.05994344 0.22346044]
 [1.7043583  1.1505651 ]
 [0.9217675  1.4614506 ]], shape=(3, 2), dtype=float32)


8. Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng
random_shuffle)

In [ ]:
X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
# Shuffle theo hàng (chiều thứ nhất)
t8 = tf.random.shuffle(X_8)
print("Bài 8 (Shuffle):\n", t8)

Bài 8 (Shuffle):
 tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)


9. Hãy tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử
dụng random_crop)

In [ ]:
# Tạo tensor (10, 10, 3) - Thường dùng cho ảnh RGB
img = tf.random.uniform([10, 10, 3])
# Cắt thành (5, 5, 3)
t9 = tf.image.random_crop(img, size=[5, 5, 3])
print("Bài 9 (Crop Shape):", t9.shape)

Bài 9 (Crop Shape): (5, 5, 3)


10. Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x + y nếu x < y, và x – y nếu x > y

In [ ]:
x = tf.random.uniform([5], minval=0, maxval=10)
y = tf.random.uniform([5], minval=0, maxval=10)

# Trả về x + y nếu x < y, ngược lại x - y
t10 = tf.where(x < y, x + y, x - y)
print("Bài 10:\nx:", x, "\ny:", y, "\nKết quả:", t10)

Bài 10:
x: tf.Tensor([0.47505736 5.4874763  2.2770715  9.39001    1.5441465 ], shape=(5,), dtype=float32) 
y: tf.Tensor([4.081793  5.9687233 6.6599903 6.0804358 6.0833883], shape=(5,), dtype=float32) 
Kết quả: tf.Tensor([ 4.5568504 11.4562     8.937061   3.3095741  7.627535 ], shape=(5,), dtype=float32)


11. Tạo ngẫu nhiên 2 tensor kích thước x = (3, 2) và giá trị trong khoảng [5, 10], y = (2, 3) và giá
trị [15, 20] tương ứng. Hãy giữ giá trị đường chéo của x và thực hiện x + y.




In [ ]:
x_11 = tf.random.uniform([3, 2], minval=5, maxval=10)
y_11 = tf.random.uniform([2, 3], minval=15, maxval=20)

# Lấy các phần tử đường chéo của x (vị trí [0,0] và [1,1])
diag_x = tf.linalg.diag_part(x_11)

# Để x + y khả thi, thường ta dùng phép nhân ma trận hoặc chuyển vị
# Giả sử thực hiện nhân ma trận (Matrix Multiplication):
res_11 = tf.matmul(x_11, y_11)

print("Bài 11:\nĐường chéo của x:", diag_x)
print("Kết quả x * y (Ma trận 3x3):\n", res_11)

Bài 11:
Đường chéo của x: tf.Tensor([7.509449 9.19331 ], shape=(2,), dtype=float32)
Kết quả x * y (Ma trận 3x3):
 tf.Tensor(
[[274.30362 272.31796 278.6823 ]
 [297.46338 295.9648  307.14307]
 [285.5918  283.56915 290.4873 ]], shape=(3, 3), dtype=float32)


12. Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng,
trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.

In [ ]:
import tensorflow as tf

# 1. Hàm tạo 2 tensor ngẫu nhiên kích thước (3, 2, 2)
def create_tensors():
    # Sử dụng phân phối đều (Uniform) từ 1 đến 10
    x = tf.random.uniform(shape=(3, 2, 2), minval=1, maxval=10)
    y = tf.random.uniform(shape=(3, 2, 2), minval=1, maxval=10)
    return x, y

# 2. Định nghĩa các hàm tính toán và chuyển vào Graph bằng @tf.function
@tf.function
def compute_all(x, y):
    """
    Hàm này thực hiện cộng, trừ, nhân, chia trong môi trường TensorFlow Graph
    """
    tong = tf.add(x, y)
    hieu = tf.subtract(x, y)
    tich = tf.multiply(x, y)
    thuong = tf.divide(x, y)

    return tong, hieu, tich, thuong



# Tạo dữ liệu
tensor_x, tensor_y = create_tensors()

# Gọi hàm đã được Graph-hóa
res_add, res_sub, res_mul, res_div = compute_all(tensor_x, tensor_y)


print("Tensor X:\n", tensor_x.numpy())
print("\nKết quả Phép Cộng (Graph mode):\n", res_add.numpy())
print("\nKết quả Phép Chia (Graph mode):\n", res_div.numpy())

Tensor X:
 [[[9.611514  1.1895603]
  [4.6458097 2.4639196]]

 [[3.6604414 4.943507 ]
  [5.991456  7.0399613]]

 [[7.5738583 9.339975 ]
  [5.66883   5.5291524]]]

Kết quả Phép Cộng (Graph mode):
 [[[17.600924   9.303186 ]
  [13.89361    9.014479 ]]

 [[ 4.9010925 13.875413 ]
  [14.220618  16.82269  ]]

 [[11.824267  13.665496 ]
  [10.366006   8.319515 ]]]

Kết quả Phép Chia (Graph mode):
 [[[1.2030319  0.14661266]
  [0.5023691  0.37613884]]

 [[2.95042    0.55346614]
  [0.72807604 0.7196317 ]]

 [[1.7819128  2.159272  ]
  [1.2068592  1.9815173 ]]]


13. Xây dựng model để tính tổng hai tensor x, y

In [ ]:
class AdditionModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    @tf.function
    def __call__(self, x, y):
        """
        Thực hiện cộng hai tensor x và y.
        Hàm __call__ cho phép sử dụng instance của class như một hàm.
        """
        return tf.add(x, y)

# 1. Khởi tạo model
sum_model = AdditionModel(name="my_sum_model")

# 2. Tạo dữ liệu mẫu (ví dụ tensor 2x2)
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# 3. Sử dụng model để tính tổng
result = sum_model(x, y)

print("Tensor x:\n", x.numpy())
print("Tensor y:\n", y.numpy())
print("Kết quả x + y:\n", result.numpy())

Tensor x:
 [[1. 2.]
 [3. 4.]]
Tensor y:
 [[5. 6.]
 [7. 8.]]
Kết quả x + y:
 [[ 6.  8.]
 [10. 12.]]


14. Xây dựng model để tính hiệu và tích hai tensor x, y

In [ ]:
class MathOpsModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    @tf.function
    def compute(self, x, y):
        """
        Thực hiện tính hiệu và tích của hai tensor.
        """
        # Tính hiệu (Difference)
        difference = tf.subtract(x, y)

        # Tính tích (Product - Element-wise)
        product = tf.multiply(x, y)

        return difference, product

# 1. Khởi tạo model
model = MathOpsModel(name="sub_mul_model")

# 2. Tạo dữ liệu mẫu (2 tensor cùng kích thước)
x = tf.constant([10.0, 20.0, 30.0])
y = tf.constant([2.0, 4.0, 5.0])

# 3. Sử dụng model để tính toán
diff, prod = model.compute(x, y)

print("Tensor x:", x.numpy())
print("Tensor y:", y.numpy())
print("-" * 30)
print("Kết quả Hiệu (x - y):", diff.numpy())
print("Kết quả Tích (x * y):", prod.numpy())

Tensor x: [10. 20. 30.]
Tensor y: [2. 4. 5.]
------------------------------
Kết quả Hiệu (x - y): [ 8. 16. 25.]
Kết quả Tích (x * y): [ 20.  80. 150.]


15. Xây dựng model để tính chu vi hình chữ nhật P = (a +b) * 2

In [ ]:
import tensorflow as tf

class RectanglePerimeterModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    @tf.function
    def compute_perimeter(self, a, b):
        """
        Tính chu vi hình chữ nhật: P = (a + b) * 2
        a: Chiều dài (Tensor)
        b: Chiều rộng (Tensor)
        """
        # Thực hiện phép cộng: (a + b)
        sum_sides = tf.add(a, b)

        # Thực hiện phép nhân với 2: (a + b) * 2
        perimeter = tf.multiply(sum_sides, 2.0)

        return perimeter



# 1. Khởi tạo model
model = RectanglePerimeterModel(name="perimeter_calculator")

# 2. Định nghĩa các cạnh (Sử dụng float32 để đảm bảo độ chính xác)
length = tf.constant(15.5, dtype=tf.float32)
width = tf.constant(7.2, dtype=tf.float32)

# 3. Gọi model để tính toán
p = model.compute_perimeter(length, width)

print(f"Chiều dài: {length.numpy()}")
print(f"Chiều rộng: {width.numpy()}")
print(f"Chu vi hình chữ nhật P = {p.numpy()}")

Chiều dài: 15.5
Chiều rộng: 7.199999809265137
Chu vi hình chữ nhật P = 45.400001525878906


16. Xây dựng model để tính diện tích toàn phần hình hộp chữ nhật
Sxung quanh = (a + b) * c * 2
Stoàn phần = (a * b) * 2 + Sxung quanh

In [ ]:
class RectangularPrismModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    @tf.function  # Chuyển đổi công thức thành đồ thị tính toán (Computation Graph)
    def compute_surface_area(self, a, b, c):
        """
        a: chiều dài
        b: chiều rộng
        c: chiều cao
        """
        # 1. Tính diện tích xung quanh: Sxung quanh = (a + b) * c * 2
        # (a + b)
        base_perimeter_half = tf.add(a, b)
        # (a + b) * c * 2
        s_xung_quanh = tf.multiply(tf.multiply(base_perimeter_half, c), 2.0)

        # 2. Tính diện tích đáy: S_đáy = a * b
        s_day = tf.multiply(a, b)

        # 3. Tính diện tích toàn phần: Stoàn phần = (a * b) * 2 + Sxung quanh
        s_toan_phan = tf.add(tf.multiply(s_day, 2.0), s_xung_quanh)

        return s_xung_quanh, s_toan_phan




model = RectangularPrismModel(name="geometry_model")

# kích thước a=5, b=3, c=4
a = tf.constant(5.0)
b = tf.constant(3.0)
c = tf.constant(4.0)

s_xq, s_tp = model.compute_surface_area(a, b, c)

print(f"Kích thước: dài={a}, rộng={b}, cao={c}")
print(f"Diện tích xung quanh: {s_xq.numpy()}")
print(f"Diện tích toàn phần: {s_tp.numpy()}")

Kích thước: dài=5.0, rộng=3.0, cao=4.0
Diện tích xung quanh: 64.0
Diện tích toàn phần: 94.0


17.  Xây dựng model chứng minh hai cạnh bên hình thang song song theo điều kiện

In [ ]:
class ParallelSidesModel(tf.Module):
    @tf.function
    def prove(self, AD, BC, AB, CD):
        # Kiểm tra hai điều kiện: AD bằng BC VÀ AB bằng CD
        condition1 = tf.equal(AD, BC)
        condition2 = tf.equal(AB, CD)

        # Nếu cả hai cùng đúng thì AD // BC
        is_parallel = tf.logical_and(condition1, condition2)
        return is_parallel

model17 = ParallelSidesModel()
# Giả sử AD=5, BC=5, AB=3, CD=3
print("Bài 17 - Hai cạnh bên có song song không?", model17.prove(5.0, 5.0, 3.0, 3.0).numpy())

Bài 17 - Hai cạnh bên có song song không? True


18. Xây dựng model chứng minh hai cạnh đáy hình thang bằng nhau theo điều kiện

In [ ]:
class EqualBasesModel(tf.Module):
    @tf.function
    def prove(self, AD, BC, is_AD_parallel_BC):
        # Kiểm tra điều kiện: AD bằng BC VÀ đã có AD // BC (đầu vào boolean)
        is_equal_bases = tf.logical_and(tf.equal(AD, BC), is_AD_parallel_BC)
        return is_equal_bases

model18 = EqualBasesModel()
# Giả sử AD=BC=5 và đã biết AD // BC
print("Bài 18 - Hai cạnh đáy có bằng nhau không?", model18.prove(5.0, 5.0, True).numpy())

Bài 18 - Hai cạnh đáy có bằng nhau không? True


19. Xây dựng model chứng minh NA = NC theo mô tả sau với AM, MB, AN, NC là đầu vào

In [ ]:
class MidpointProofModel(tf.Module):
    @tf.function
    def prove(self, AM, MB, is_MN_parallel_BC):
        """
        Đầu vào: Độ dài AM, MB và trạng thái song song của MN với BC
        Trả về: True nếu đủ điều kiện kết luận NA = NC
        """
        # Điều kiện 1: M là trung điểm AB
        is_M_midpoint = tf.equal(AM, MB)

        # Kết luận NA = NC nếu (M là trung điểm) VÀ (MN // BC)
        can_conclude_N_midpoint = tf.logical_and(is_M_midpoint, is_MN_parallel_BC)
        return can_conclude_N_midpoint

model19 = MidpointProofModel()
# Giả sử AM=2, MB=2 và MN // BC là đúng
result = model19.prove(2.0, 2.0, True)
print("Bài 19 - Có thể kết luận NA = NC không?", result.numpy())

Bài 19 - Có thể kết luận NA = NC không? True
