<a href="https://colab.research.google.com/github/DinhThanh-Dat/ThucHanhDeepLearning/blob/main/Baitaptuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bai Numpy

In [ ]:
import numpy as np
# tao numpy arry
# mang 1 chieu
mylist = [1,2,3,4]
print('Python list',mylist)
numpy_arr = np.array(mylist)
print('Numpy array',numpy_arr)
print('==================\n')

#mang 2 chieu
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)
print('==================\n')

#mang 3 chieu
d=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(d)
print(d.shape)

Python list [1, 2, 3, 4]
Numpy array [1 2 3 4]

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1
e=np.zeros((2,2))
f=np.ones((4,4))
print('Zero: \n',e)
print('One: \n',f)


Zero: 
 [[0. 0.]
 [0. 0.]]
One: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Thay đổi kích thước ma trận
e=np.array([[1,2,3],[4,5,6]])
print(e)

f=e.reshape(3,2)
print('Reshape: \n',f)
print('============\n')
g = np.array([[(1,2,3),(4,5,6)],
             [(7,8,9),(10,11,12)]
             ])
print(g)
print('reshape:\n',g.shape)

h = g.reshape(3,4)
print('reshape(3,4):\n',h)

j = g.reshape(3,2,2)
print('reshape(3,2,2):\n',j)

k=g.reshape(2,3,2)
print('reshape(2,3,2):\n',k)


[[1 2 3]
 [4 5 6]]
Reshape: 
 [[1 2]
 [3 4]
 [5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
reshape:
 (2, 2, 3)
reshape(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape(3,2,2):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
reshape(2,3,2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#chuyển array nhiều chiều về 1 chiều
e=np.array([(1,2,3),(4,5,6)])
f=e.flatten()
print(f)

g=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
j=g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Thêm dòng dữ liệu với hstack và vstack
f=np.array([(1,2,3),(4,5,6)])
g=np.array([(7,8,9),(10,11,12)])
h=np.vstack((f,g))
print('Horizontal Append\n',h)
i=np.hstack((f,g))
print('Vertical Append\n',i)

Horizontal Append
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vertical Append
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


##Sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np
a = np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b = np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c = np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [69 91 38 66 74]
Random 2-D array
 [[33 83 19 51]
 [69 23  4 98]
 [14 40 21 17]]
Random 3-D array
 [[[21 25 48]
  [76 55 59]
  [41 87 14]
  [13 67 74]]

 [[ 3 61 28]
  [27  2 91]
  [ 3 54 84]
  [15 97 74]]

 [[91 43 16]
  [93 66 56]
  [87 77 13]
  [62 59 66]]]


##Sinh mảng số thực trong khoảng [0, 1]

In [ ]:
a = np.random.rand(5)
print('Random 1-D array\n',a)
b = np.random.rand(3,4)
print('Random 2-D array\n',b)
c = np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.31792836 0.42082683 0.61340472 0.97502243 0.59683843]
Random 2-D array
 [[0.29476278 0.41576578 0.28837485 0.39984892]
 [0.65343521 0.74220514 0.08314377 0.52393819]
 [0.70957077 0.20180779 0.40804613 0.69971831]]
Random 3-D array
 [[[0.77164265 0.73569035 0.32925238]
  [0.89637054 0.93499516 0.7098429 ]
  [0.07024965 0.55263389 0.11991733]
  [0.15391967 0.0431022  0.22925579]]

 [[0.99734518 0.41614728 0.37595022]
  [0.54451991 0.07175131 0.2240159 ]
  [0.35897071 0.67449539 0.86089888]
  [0.98134568 0.71840127 0.45835358]]

 [[0.98959303 0.15679683 0.66366364]
  [0.22428254 0.29129992 0.48470037]
  [0.74557544 0.85980994 0.30611892]
  [0.56392906 0.21852149 0.98742839]]]


Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
a = np.random.normal(5,0.5,10)
print(a)

[4.41723719 5.72652408 4.35549481 4.83435475 5.08017554 5.31240972
 5.3565249  4.66766965 4.85726617 4.85193152]


##Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)

b = np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)

8
[[12 18  2  8 16]
 [12 10 10 20  6]
 [ 8 16 10  8  8]]


##Thay đổi giá trị của ma trận

In [ ]:
A = np.matrix(np.ones((5,5)))
print('The matrix\n',A)
np.array(A)[2] = 2
print('Change values of third row with array\n',A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##Sinh dãy số theo khoảng cho trước
###Dùng hàm arange

In [ ]:
#tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1,20)
print(a)

#tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1,20,2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### Dùng hàm linspace

In [ ]:
a = np.linspace(1,5,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


##Index và slice

In [ ]:
#slide
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:',a[0])
print('second row:',a[1])

#indexing
print('second column:',a[:,1])
print('first column:',a[:,0])
print('First two values of second row:', a[1,:2])



[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


#Bai PANDAS

In [16]:
import pandas as pd
#Tao pandas series tư list
a = pd.Series([1,2,3])
print(a)
print('First value:', a[0])
b = pd.Series([1,2,3],index=['a','b','c'])
print(b)
print('First value:',b['a'])
#Tao pandas series tu dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1
1    2
2    3
dtype: int64
First value: 1
a    1
b    2
c    3
dtype: int64
First value: 1
day1    420
day2    380
day3    390
dtype: int64


##TẠO ĐỐI TƯỢNG DATAFRAME
###DataFrame là mảng 2-chiều có nhãn ở 2 trục

In [17]:
h = np.array([[1,2],[3,4]])
df_h = pd.DataFrame(h)
print('DataFrame\n',df_h)

numpy_h = np.array(df_h)
print('Munpy array:\n',numpy_h)

DataFrame
    0  1
0  1  2
1  3  4
Munpy array:
 [[1 2]
 [3 4]]


###Tạo DataFrame mảng 2-chiều có tên cột

In [19]:
dic = {'Name':['John', 'Smith'],'Age':[30,40]}
df = pd.DataFrame(dic)
print(df)

#tao mang 20 x 4
r = np.random.randn(20,4)
df = pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head()) # in 5 dong dau tien
#


    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0 -0.596673  0.717880  0.473530 -0.665171
1  0.913026 -1.400002 -1.123679 -0.961991
2 -0.862822 -0.226439 -1.181613 -0.139259
3 -0.836565 -0.178001 -0.668313 -0.656787
4 -0.559978  2.210645  0.646549 -0.009999


###Slice DataFrame

In [20]:
#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  #in 5 dòng đầu tiên

#chọn 1 cột
print('Chọn cột so1\n', df['so1'])

#chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

#chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

#chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

#Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -1.067409  0.244046  1.176908  0.023624
1 -0.244754  1.081917  1.216733 -1.706044
2 -1.366678  1.610019  0.649939  0.116620
3  2.040210  0.551901 -0.058917  1.289878
4 -0.150427 -0.080637  0.660934 -2.036406
Chọn cột so1
 0    -1.067409
1    -0.244754
2    -1.366678
3     2.040210
4    -0.150427
5    -0.115337
6    -0.179948
7    -1.141463
8     1.077770
9     0.651259
10   -0.763751
11    1.022841
12   -0.944834
13    1.064817
14    0.014561
15    1.933591
16    0.642434
17   -0.784759
18   -1.617846
19   -1.091596
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -1.067409  0.244046  1.176908  0.023624
1 -0.244754  1.081917  1.216733 -1.706044
2 -1.366678  1.610019  0.649939  0.116620
Chọn nhiều cột
          so1       so3
0  -1.067409  1.176908
1  -0.244754  1.216733
2  -1.366678  0.649939
3   2.040210 -0.058917
4  -0.150427  0.660934
5  -0.115337 -0.103147
6  -0.179948 -0.597528
7  -1.141463  0.012153


### Nối nhiều DataFrame

In [21]:
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])

df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

#Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

#Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


#Bai TENSORFLOW
##Tensor 0-chiều

In [24]:
import tensorflow as tf

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [25]:
# This will be an int32 tensor by default;
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


## Tensor 1-chiều

In [26]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


##Tensor 2-chiều (ma trận)

In [27]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


##Tensor n-chiều (nhiều trục)

In [29]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


##Tạo tensor tự động gán giá trị 0 ban đầu

In [30]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


##Tạo tensor tự động gán giá trị 1 ban đầu

In [31]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


##Tạo tensor tự động với giá trị bất kỳ

In [32]:
t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


##Tạo tensor 1-chiều với hàm linspace

In [33]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


##Tạo tensor 1-chiều với hàm range

In [34]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)


range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)
